#!/bin/bash

cat <<_EOF
[server]
# Port to listen on. There is no default as this parameter is used by different components,
# for example, Router/Hub/Standalone will use 4444 and Node will use 5555.
port = 4444
# Whether the server should bind to the host address/name, or only use it to" report its reachable url.
# Helpful in complex network topologies where the server cannot report itself with the current IP/hostname
# but rather an external IP or hostname (e.g. inside a Docker container)
#bind-host = true

# Maximum number of listener threads. Default value is: (available processors) * 3.
# max-threads = 24

[sessionqueue]
# Timeout in seconds. A new incoming session request is added to the queue.
# Requests sitting in the queue for longer than the configured time will timeout.
session-request-timeout = $GRID_NEW_SESSION_WAIT_TIMEOUT

# Retry interval in seconds. If all slots are busy, new session request will be retried after the given interval.
# session-retry-interval = 5

[distributor]
# Full class name of non-default slot matcher to use.
# This is used to determine whether a Node can support a particular session.
slot-matcher = "com.zebrunner.mcloud.grid.MobileCapabilityMatcher"

# How often, in seconds, will the health check run for all Nodes.
# This ensures the server can ping all the Nodes successfully.
healthcheck-interval = $GRID_CLEAN_UP_CYCLE

# Allow the Distributor to reject a request immediately if the Grid does not support the requested capability.
# Rejecting requests immediately is suitable for a Grid setup that does not spin up Nodes on demand.
reject-unsupported-caps = $GRID_THROW_ON_CAPABILITY_NOT_PRESENT

[logging]
# Log level. Default logging level is INFO. Log levels are described here https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
log-level = "INFO"

[network]
# Relax checks on origin header and content type of incoming requests, in contravention of strict W3C spec compliance.
relax-checks = true
_EOF
