handlers=java.util.logging.ConsoleHandler

# Default global logging level
.level= WARNING

com.zebrunner.level=INFO
java.util.logging.ConsoleHandler.level = INFO

# Selenium logs the whole capabilities map of a slot for every new session attempt
org.openqa.grid.internal.TestSlot.level=WARNING
